version: 2.0

defaults: &defaults
  docker:
    - image: circleci/android:api-27-alpha
  working_directory: ~/android-template
  environment:
    _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
    TERM: dumb

update_sdk: &update_sdk
  name: Update SDK
  command: |
    mkdir "$ANDROID_HOME/licenses" || true
    echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
    echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    sdkmanager "platform-tools" "platforms;android-27"

jobs:
  test:
    <<: *defaults
    steps:
      - run:
          <<: *update_sdk

      - checkout

      - run:
          name: Update apt-get
          command: sudo apt-get update

      - run:
          name: Install cookiecutter
          command: sudo apt-get install cookiecutter

      - run:
          name: Provide script permissions
          command: chmod 777 ci_script.sh

      - run:
          name: Run tests
          command: ./ci_script.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - test