version: 2.0

defaults: &defaults
  docker:
    - image: circleci/android:api-27-alpha
  working_directory: ~/{{ cookiecutter.repo_name }}
  environment:
    _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
    TERM: dumb
{% raw %}
cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
{% endraw %}
update_sdk: &update_sdk
  name: Update SDK
  command: |
    mkdir "$ANDROID_HOME/licenses" || true
    echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
    echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    sdkmanager "platform-tools" "platforms;android-27"

download_dependencies: &download_dependencies
  name: Download Dependencies
  command: ./gradlew dependencies --no-daemon

run_tests: &run_tests
  name: Run Tests
  command: ./gradlew check --no-daemon

reports_artifacts: &reports_artifacts
  path: app/build/reports
  destination: reports

apk_artifacts: &apk_artifacts
  path: app/build/outputs/apk
  destination: apk

jobs:
  test:
    <<: *defaults
    steps:
      - run:
          <<: *update_sdk

      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          <<: *download_dependencies

      - run:
          <<: *run_tests

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - store_artifacts:
          <<: *reports_artifacts

      - store_test_results:
          path: app/build/test-results

      - persist_to_workspace:
          root: .
          paths:
            - .gradle
            - build
            - app/build

  develop:
    <<: *defaults
    steps:
      - run:
          <<: *update_sdk

      - checkout

      - restore_cache:
          <<: *cache_key

      - attach_workspace:
          at: ~/{{ cookiecutter.repo_name }}

      - run:
          name: Deploy to develop track on HockeyApp
          command: ./gradlew app:uploadDevelopReleaseToHockeyApp --info --no-daemon

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - store_artifacts:
          <<: *apk_artifacts

  sprint:
    <<: *defaults
    steps:
      - run:
          <<: *update_sdk

      - checkout

      - restore_cache:
          <<: *cache_key

      - attach_workspace:
          at: ~/{{ cookiecutter.repo_name }}

      - run:
          name: Deploy to sprint track on HockeyApp
          command: ./gradlew app:uploadSprintReleaseToHockeyApp --info --no-daemon

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - store_artifacts:
          <<: *apk_artifacts

  beta:
    <<: *defaults
    steps:
      - run:
          <<: *update_sdk

      - checkout

      - restore_cache:
          <<: *cache_key

      - attach_workspace:
          at: ~/{{ cookiecutter.repo_name }}

      - run:
          name: Deploy to beta track on HockeyApp
          command: ./gradlew app:uploadBetaReleaseToHockeyApp --info --no-daemon

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - store_artifacts:
          <<: *apk_artifacts

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - develop:
          requires:
            - test
          filters:
            branches:
              only: develop
      - sprint:
          requires:
            - test
          filters:
            tags:
              only: /sprint-.*/
            branches:
              ignore: /.*/
      - beta:
          requires:
            - test
          filters:
            tags:
              only: /release-.*/
            branches:
              ignore: /.*/